// Generated by Xata Codegen 0.23.5. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "subscriber",
    columns: [
      { name: "email_address", type: "email", unique: true },
      {
        name: "tech_subscribed",
        type: "int",
        notNull: true,
        defaultValue: "0",
      },
      { name: "web_subscribed", type: "int", notNull: true, defaultValue: "0" },
      {
        name: "crypto_subscribed",
        type: "int",
        notNull: true,
        defaultValue: "0",
      },
      { name: "verified", type: "int", notNull: true, defaultValue: "0" },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Subscriber = InferredTypes["subscriber"];
export type SubscriberRecord = Subscriber & XataRecord;

export type DatabaseSchema = {
  subscriber: SubscriberRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://Maiko-Miyazaki-s-workspace-im8jpk.eu-west-1.xata.sh/db/techmatome",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
