name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18.x

    - name: Install dependencies on root
      run: npm install
      
    - name: Install dependencies on package
      run: |
        cd packages
        npm install
        cd ..

    - name: Run unit tests
      run: npm test
      env:
        DB_API_KEY: ${{ secrets.DB_API_KEY }}
        DB_BRANCH: ${{ secrets.DB_BRANCH }}
        AWS_ACCT_ID: ${{ secrets.AWS_ACCT_ID }}
        WORKMAIL_ORG_ID: ${{ secrets.WORKMAIL_ORG_ID }}
        PUBLIC_DOMAIN: ${{ secrets.PUBLIC_DOMAIN }}
        CIPHER_ALGO: ${{ secrets.CIPHER_ALGO }}
        CIPHER_KEY: ${{ secrets.CIPHER_KEY }}
        CIPHER_IV: ${{ secrets.CIPHER_IV }}

    - name: Deploy to prod
      run: npx --no-install sst deploy --stage prod
      env:
        DB_API_KEY: ${{ secrets.DB_API_KEY }}
        DB_BRANCH: ${{ secrets.DB_BRANCH }}
        AWS_ACCT_ID: ${{ secrets.AWS_ACCT_ID }}
        WORKMAIL_ORG_ID: ${{ secrets.WORKMAIL_ORG_ID }}
        PUBLIC_DOMAIN: ${{ secrets.PUBLIC_DOMAIN }}
        CIPHER_ALGO: ${{ secrets.CIPHER_ALGO }}
        CIPHER_KEY: ${{ secrets.CIPHER_KEY }}
        CIPHER_IV: ${{ secrets.CIPHER_IV }}
